import os
from dotenv import load_dotenv

load_dotenv()

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

STREAMERS = [
    "1S55RKSJ",
    "ADEKVAT01",
    "ADEKVAT02",
    "F4SVC69D",
    "GG2BQD8I",
    "LOLLY",
    "LOLLY10",
    "LOLLY11",
    "LOLLY12",
    "MAGER01",
    "NEKVJE7O",
    "NXL1OTTM",
    "PUXG5EU7",
    "UFC329",
    "YL5PAE25",
    "acool",
    "acool1",
    "acool2",
    "acool3",
    "acool4",
    "acool5",
    "acool6",
    "acool7",
    "adam",
    "aunkere",
    "aunkere1",
    "avice",
    "betmens",
    "bolt",
    "brokeboys",
    "cct1",
    "danila.gorilla",
    "dotairy",
    "dyrachyo",
    "ewc",
    "ewc1",
    "Gorilla",
    "krat",
    "krip",
    "koma",
    "koma1",
    "koma2",
    "kyzko",
    "mael",
    "mael2",
    "mantis",
    "mantis1",
    "mantis2",
    "neret",
    "neclas",
    "nix",
    "nix1",
    "nix3",
    "nix4",
    "nix5",
    "nix6",
    "nix7",
    "nix8",
    "nix9",
    "papa",
    "pandafx5",
    "pomidor",
    "pomidor1",
    "pomidor2",
    "relax",
    "risen",
    "shoke",
    "solo",
    "solo1",
    "solo10",
    "solo11",
    "solo2",
    "solo3",
    "solo4",
    "solo5",
    "solo6",
    "solo7",
    "solo8",
    "solo9",
    "solotg",
    "staya",
    "staya1",
    "stray",
    "strayufc",
    "sweet",
    "sysman",
    "torontotokyo",
    "vovapain",
    "zonertg",
    "zonertg1",
    "zonertg10",
    "zonertg11",
    "zonertg12",
    "zonertg13",
    "zonertg14",
    "zonertg15",
    "zonertg16",
    "zonertg2",
    "zonertg3",
    "zonertg4",
    "zonertg5",
    "zonertg6",
    "zonertg7",
    "zonertg8",
    "zonertg9",
]

CHECK_INTERVAL = 60
URL_TEMPLATE = "https://betboom.ru/freestream/{}"
